server:
  port: 8082

spring:
  application:
    name: inventory-service
  rabbitmq:
    host: localhost
    port: 5672
  mongodb:
      uri: mongodb://localhost:27017/inventorydb
management:
  endpoints:
    web:
      exposure:
        include: health,info
saga:
  events:
    exchange: saga.events
    order-placed-queue: inventory.order.placed
    order-failed-queue: inventory.order.failed
    order-confirmed-queue: inventory.order.confirmed
